# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]


jobs:
   test:
     runs-on: ubuntu-latest
     steps:
     - name: set ENV_ONE
       run: echo "ENV_ONE=$(echo $"v0.0.1" | cut -c 2-)" >> $GITHUB_ENV
     - name: set prefix env
       run: echo "PREFIX=$(echo $"prifix")" >> $GITHUB_ENV
     - name: check ENV_ONE
       run: echo ${{ env.ENV_ONE }}
     - name: check PREFIX 
       run: echo ${{ env.PREFIX }}
     - name: set CONCAT
       run: echo "CONCAT=${{ env.PREFIX }}${{ env.ENV_ONE }}" >> $GITHUB_ENV
     - name: chek CONCAT
       run: echo ${{ env.CONCAT }}
     - name: Set prefix
       run: echo "PREFIX_2=$(echo $"pgCodeKeeper-")" >> $GITHUB_ENV
     - name: ser Lin postfix
       run: echo "LINUX=$(echo $"-linux.gtk.x86_64.tar.gz")" >> $GITHUB_ENV

     - name: set linux build name
       run: echo "LINUX_BUILD=${{ env.PREFIX_2}}${{ env.ENV_ONE }}-linux.gtk.x86_64.tar.gz" >> $GITHUB_ENV

     - name: check linux build name
       run: echo ${{ env.LINUX_BUILD }}

     - name: Set color
       id: color-selector
       run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
     - name: Get color
       env:
         SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
       run: echo "The selected color is $SELECTED_COLOR"
