# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ "main" ]


jobs:
   test:
     runs-on: ubuntu-latest
     steps:
     - name: set ENV_ONE
       run: echo "ENV_ONE=$(echo $"v0.0.1" | cut -c 2-)" >> $GITHUB_ENV
     - name: check ENV_ONE
       run: echo ${{ env.ENV_ONE }}
