name: Release Workflow

on:
  push:
    tag:
      -'v*.*.*'

jobs:
   build:

      runs-on: ubuntu-latest

      steps:
      - name: create GitHub release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: test 1
          draft: false
          prerelease: false
